---
- name: Gather system information and services
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get IP address
      ansible.builtin.set_fact:
        ip_address: "{{ ansible_default_ipv4.address }}"

    - name: Get OS version
      ansible.builtin.set_fact:
        os_version: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Get hostname using uname -n
      ansible.builtin.command:
        cmd: uname -n
      register: uname_output

    - name: Set hostname fact
      ansible.builtin.set_fact:
        hostname: "{{ uname_output.stdout }}"

    - name: Format data for CSV
      ansible.builtin.set_fact:
        csv_data: "{{ hostname }},{{ ip_address }},{{ os_version }}"

    - name: Check for running database services
      shell: |
        for db in oracle db2sysc mysqld mariadbd mongod postgres redis-server cassandra; do
          if pgrep -x $db > /dev/null; then
            echo "$db is running"
          fi
        done
      register: db_services

    - name: Get database versions
      shell: |
        if pgrep -x oracle > /dev/null; then
          echo "Oracle DB version: $(sqlplus -v)"
        elif pgrep -x db2sysc > /dev/null; then
          echo "DB2 version: $(db2level)"
        elif pgrep -x mysqld > /dev/null; then
          echo "MySQL version: $(mysql --version)"
        elif pgrep -x mariadbd > /dev/null; then
          echo "MariaDB version: $(mysql --version)"
        elif pgrep -x mongod > /dev/null; then
          echo "MongoDB version: $(mongod --version | grep 'db version' | awk '{print $3}')"
        elif pgrep -x postgres > /dev/null; then
          echo "PostgreSQL version: $(psql --version)"
        elif pgrep -x redis-server > /dev/null; then
          echo "Redis version: $(redis-server --version | awk '{print $3}')"
        elif pgrep -x cassandra > /dev/null; then
          echo "Cassandra version: $(cassandra -v)"
        else
          echo "No database is running"
        fi
      register: db_versions

    - name: Check PHP version
      shell: |
        if command -v php > /dev/null 2>&1; then
          echo "PHP version: $(php -v | grep -oP '^PHP \K[0-9]+\.[0-9]+\.[0-9]+')"
        else
          echo "PHP is not installed on this system."
        fi
      register: php_version

    - name: Check for running web services
      shell: |
        for service in httpd apache2 nginx tomcat lighttpd caddy openresty wildfly jetty glassfish node gunicorn uwsgi; do
          if pgrep -x $service > /dev/null; then
            echo "$service is running"
          fi
        done
      register: web_services

    - name: Create output file with gathered information
      ansible.builtin.copy:
        content: |
          Database Information:
          ----------------------
          {{ db_services.stdout }}

          Database Versions:
          ------------------
          {{ db_versions.stdout }}

          PHP Version:
          ------------
          {{ php_version.stdout }}

          Web Services Status:
          --------------------
          {{ web_services.stdout }}
        dest: "/home/svc_aux/{{ inventory_hostname }}.txt"

- name: Update central server with gathered information
  hosts: 10.1.34.26
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
    - name: Ensure directory exists on central server
      ansible.builtin.file:
        path: /home/svc_aux/backup/All_Servers_information
        state: directory
        mode: '0775'
        owner: root
        group: root

    - name: Create or truncate CSV file with header
      ansible.builtin.copy:
        content: "Hostname,IP Address,OS Version,Database Information,Database Version,PHP Version,Web Services\n"
        dest: "/home/svc_aux/backup/All_Servers_information/All_server_information.csv"
        mode: '0664'
        owner: svc_aux
        group: svc_aux

    - name: Check if output file exists on remote server
      ansible.builtin.stat:
        path: "/home/svc_aux/{{ inventory_hostname }}.txt"
      register: file_stat

    - name: Fetch output file from remote server if exists
      ansible.builtin.fetch:
        src: "/home/svc_aux/{{ inventory_hostname }}.txt"
        dest: "/tmp/"
        flat: yes
      when: file_stat.stat.exists

    - name: Append gathered information to central CSV file
      ansible.builtin.lineinfile:
        path: "/home/svc_aux/backup/All_Servers_information/All_server_information.csv"
        line: "{{ hostvars[inventory_hostname]['csv_data'] }}"
      loop: "{{ groups['all'] }}"
      when: hostvars[inventory_hostname]['csv_data'] is defined
