---
- name: Gather system information and save to CSV
  hosts: all
  tasks:

    - name: Gather server facts
      ansible.builtin.setup:

    - name: Generate CSV data for each server
      ansible.builtin.set_fact:
        csv_data: "{{ inventory_hostname }},{{ ansible_default_ipv4.address }},{{ ansible_distribution }},{{ ansible_distribution_version }}"

    - name: Create directory for storing server information
      ansible.builtin.file:
        path: /home/svc_aux/backup/All_Servers_information
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Create CSV file if not present
      ansible.builtin.file:
        path: /home/svc_aux/backup/All_Servers_information/All_server_information.csv
        state: touch
        mode: '0644'
      delegate_to: localhost

    - name: Append gathered information to CSV file
      ansible.builtin.lineinfile:
        path: "/home/svc_aux/backup/All_Servers_information/All_server_information.csv"
        line: "{{ hostvars[item]['csv_data'] }}"
      loop: "{{ groups['all'] }}"
      when: 
        - hostvars[item]['csv_data'] is defined
        - item != '10.1.34.26'

    - name: Display skipped message for excluded server
      debug:
        msg: "Server {{ inventory_hostname }} is skipped from CSV update."
      when: inventory_hostname == '10.1.34.26'
