---
- name: Check disk usage on all filesystems and transfer the report
  hosts: "{{ hosts | default('all') }}"
  gather_facts: no
  tasks:

    # Check disk usage for all filesystems
    - name: Get disk usage for all filesystems
      shell: df -h --output=target,pcent | tail -n +2
      register: disk_usage_all

    # Format the disk usage output into a text file
    - name: Create a disk usage report
      copy:
        content: |
          Disk Usage Report for {{ inventory_hostname }}
          ----------------------------------------
          Filesystem    Usage (%)
          {% for line in disk_usage_all.stdout_lines %}
          {{ line.split()[0] }}    {{ line.split()[1] }}
          {% endfor %}
        dest: /tmp/disk_usage_{{ inventory_hostname }}.txt

    # Transfer the report to the remote server
    - name: Transfer the disk usage report to the remote server
      copy:
        src: /tmp/disk_usage_{{ inventory_hostname }}.txt
        dest: /home/svc_aux/backup/Diskspace/disk_usage_{{ inventory_hostname }}.txt
        remote_src: no
      delegate_to: 10.1.34.26

    # Clean up the temporary file on the local server
    - name: Clean up the temporary file
      file:
        path: /tmp/disk_usage_{{ inventory_hostname }}.txt
        state: absent
