---
- name: Check disk usage and generate report
  hosts: "{{ hosts | default('all') }}"
  gather_facts: no
  tasks:

    - name: Get disk usage for all filesystems
      shell: df -h --output=target,pcent | tail -n +2
      register: disk_usage_all

    - name: Analyze disk usage and generate a report
      set_fact:
        disk_report: |
          HOSTNAME: {{ inventory_hostname }}
          {% set critical_filesystems = [] %}
          {% for line in disk_usage_all.stdout_lines %}
            {% set mount, usage = line.split() %}
            {% set usage_percent = usage[:-1] | int %}
            {% if usage_percent > 80 %}
              {{ critical_filesystems.append(mount) }}
            {% endif %}
          {% endfor %}
          
          {% if critical_filesystems | length > 0 %}
          The following file systems crossed 80% usage:
          {% for fs in critical_filesystems %}
          - {{ fs }}
          {% endfor %}
          {% else %}
          All file systems are good
          {% endif %}

    - name: Save disk report to file
      copy:
        content: "{{ disk_report }}"
        dest: /tmp/disk_usage_{{ inventory_hostname }}.txt

    - name: Fetch the report file from remote hosts to the AWX controller
      fetch:
        src: /tmp/disk_usage_{{ inventory_hostname }}.txt
        dest: /tmp/
        flat: yes

    - name: Transfer the report from AWX controller to the remote server
      copy:
        src: /tmp/disk_usage_{{ inventory_hostname }}.txt
        dest: /home/svc_aux/backup/Diskspace/disk_usage_{{ inventory_hostname }}.txt
        remote_src: no
      delegate_to: 10.1.34.26

    - name: Clean up temporary report file on the remote host
      file:
        path: /tmp/disk_usage_{{ inventory_hostname }}.txt
        state: absent
