---
- name: Gather system information and create consolidated CSV
  hosts: all
  gather_facts: yes
  tasks:
    - name: Gather server information
      ansible.builtin.set_fact:
        server_info: "{{ ansible_hostname }},{{ ansible_default_ipv4.address }},{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Append server information to the consolidated CSV
      ansible.builtin.lineinfile:
        path: /tmp/all_server_info.csv
        line: "{{ server_info }}"
        create: yes
      delegate_to: localhost
      run_once: false

- name: Copy consolidated CSV to central server
  hosts: 10.1.34.26
  become: yes
  become_method: sudo
  become_user: root
  vars:
    ansible_become_pass: just44now
  tasks:
    - name: Ensure target directory exists
      ansible.builtin.file:
        path: /home/svc_aux/backup/All_Servers_information
        state: directory
        mode: '0755'
        owner: svc_aux
        group: svc_aux

    - name: Copy consolidated server information to central server
      ansible.builtin.copy:
        src: /tmp/all_server_info.csv
        dest: /home/svc_aux/backup/All_Servers_information/All_server_information.csv
        owner: svc_aux
        group: svc_aux
        mode: '0644'

    - name: Add header to the CSV file
      ansible.builtin.lineinfile:
        path: /home/svc_aux/backup/All_Servers_information/All_server_information.csv
        line: "Hostname,IP Address,OS Version"
        insertbefore: BOF
        create: yes

    - name: Clean up temporary files on the Controller
      ansible.builtin.file:
        path: /tmp/all_server_info.csv
        state: absent
      delegate_to: localhost
