---
- name: Gather system information
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get IP address
      ansible.builtin.set_fact:
        ip_address: "{{ ansible_default_ipv4.address }}"

    - name: Get OS version
      ansible.builtin.set_fact:
        os_version: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Get hostname using uname -n
      ansible.builtin.command:
        cmd: uname -n
      register: uname_output

    - name: Set hostname fact
      ansible.builtin.set_fact:
        hostname: "{{ uname_output.stdout }}"

- name: Update central CSV file
  hosts: 10.1.34.26
  become: yes
  become_method: sudo
  become_user: root
  vars:
    ansible_become_pass: just44now
  tasks:
    - name: Ensure directory exists
      ansible.builtin.file:
        path: /home/svc_aux/backup/All_Servers_information
        state: directory
        mode: '0755'
        owner: svc_aux
        group: svc_aux

    - name: Create CSV file with proper formatting
      community.general.ini_file:
        path: "/home/svc_aux/backup/All_Servers_information/All_server_information.csv"
        section: null
        option: "{{ item.hostname }}"
        value: "{{ item.ip_address }},{{ item.os_version }}"
        allow_no_value: false
        create: yes
      loop: "{{ groups['all'] | map('extract', hostvars) | list }}"
      loop_control:
        label: "{{ item.hostname }}"

    - name: Ensure correct ownership of the CSV file
      ansible.builtin.file:
        path: "/home/svc_aux/backup/All_Servers_information/All_server_information.csv"
        owner: svc_aux
        group: svc_aux
        mode: '0644'

    - name: Add header to CSV file
      ansible.builtin.lineinfile:
        path: "/home/svc_aux/backup/All_Servers_information/All_server_information.csv"
        line: "Hostname,IP Address,OS Version"
        insertbefore: BOF

    - name: Replace equal signs with commas
      ansible.builtin.replace:
        path: "/home/svc_aux/backup/All_Servers_information/All_server_information.csv"
        regexp: '='
        replace: ','
