---
- name: Gather system information
  hosts: all
  gather_facts: yes
  tasks:
    - name: Gather server information
      ansible.builtin.set_fact:
        server_info: |
          {{ ansible_hostname }},{{ ansible_default_ipv4.address }},{{ ansible_distribution }} {{ ansible_distribution_version }}
      delegate_to: localhost
      run_once: true

    - name: Append server information to a temporary file
      ansible.builtin.lineinfile:
        path: /tmp/all_server_info.csv
        line: "{{ server_info }}"
        create: yes
        state: present

- name: Consolidate CSV on central server
  hosts: 10.1.34.26
  become: yes
  become_method: sudo
  become_user: root
  vars:
    ansible_become_pass: just44now
  tasks:
    - name: Ensure target directory exists
      ansible.builtin.file:
        path: /home/svc_aux/backup/All_Servers_information
        state: directory
        mode: '0755'
        owner: svc_aux
        group: svc_aux

    - name: Copy gathered server information to the central CSV
      ansible.builtin.copy:
        src: /tmp/all_server_info.csv
        dest: /home/svc_aux/backup/All_Servers_information/All_server_information.csv
        remote_src: no
        owner: svc_aux
        group: svc_aux
        mode: '0644'

    - name: Add header to the CSV file
      ansible.builtin.lineinfile:
        path: /home/svc_aux/backup/
