---
- name: List available patches for Linux servers
  hosts: all
  become: yes
  vars:
    remote_server: "10.1.34.26"
    remote_path: "/home/svc_aux/backup/patchinformation/patchlist.csv"
  tasks:
    - name: Identify the Linux distribution
      ansible.builtin.shell: |
        if [ -f /etc/os-release ]; then
          . /etc/os-release && echo $ID
        else
          echo "unknown"
        fi
      register: distro
      changed_when: false

    - name: List available updates for Red Hat-based systems
      when: distro.stdout in ["rhel", "centos", "rocky", "almalinux"]
      ansible.builtin.shell: |
        if command -v dnf > /dev/null 2>&1; then
          dnf check-update
        else
          yum check-update
        fi
      register: redhat_updates
      failed_when: redhat_updates.rc not in [0, 100]
      changed_when: false

    - name: List available updates for Debian-based systems
      when: distro.stdout in ["debian", "ubuntu"]
      ansible.builtin.shell: |
        apt update -qq && apt list --upgradable 2>/dev/null
      register: debian_updates
      failed_when: false
      changed_when: false

    - name: Ensure the remote directory exists
      ansible.builtin.file:
        path: "{{ remote_path | dirname }}"
        state: directory
        mode: '0755'
      delegate_to: "{{ remote_server }}"

    - name: Append patch information to the remote CSV file
      ansible.builtin.lineinfile:
        path: "{{ remote_path }}"
        line: |
          {% if distro.stdout in ["rhel", "centos", "rocky", "almalinux"] %}
          {% for line in redhat_updates.stdout_lines %}
          {{ inventory_hostname }},{{ line | regex_replace(' +', ',') }}
          {% endfor %}
          {% elif distro.stdout in ["debian", "ubuntu"] %}
          {% for line in debian_updates.stdout_lines if not line.startswith('Listing...') %}
          {{ inventory_hostname }},{{ line | regex_replace(' +', ',') }}
          {% endfor %}
          {% else %}
          {{ inventory_hostname }},Unsupported Linux Distribution ({{ distro.stdout }})
          {% endif %}
        create: yes
        state: present
      delegate_to: "{{ remote_server }}"
