---
- name: Check for available updates on Debian and RedHat systems
  hosts: all
  become: yes
  tasks:
    - name: Gather facts about the system
      ansible.builtin.gather_facts:

    - name: Debug OS family
      debug:
        msg: "System OS family: {{ ansible_facts['os_family'] }}"

    - name: Check for available updates on Debian-based systems
      shell: apt list --upgradable
      when: ansible_facts['os_family'] == 'Debian'
      register: debian_updates
      ignore_errors: yes

    - name: Show Debian system update list
      debug:
        msg: "{{ debian_updates.stdout }}"
      when: ansible_facts['os_family'] == 'Debian'

    - name: Check for available updates on RedHat-based systems
      shell: yum check-update
      when: ansible_facts['os_family'] == 'RedHat'
      register: redhat_updates
      ignore_errors: yes

    - name: Show RedHat system update list
      debug:
        msg: "{{ redhat_updates.stdout }}"
      when: ansible_facts['os_family'] == 'RedHat'
