---
- name: Check and list available updates for all servers
  hosts: all
  gather_facts: true

  tasks:
    - name: Check for updates on Rocky Linux
      shell: "dnf list updates"
      when: ansible_facts['os_family'] == 'RedHat'
      register: dnf_updates
      ignore_errors: true

    - name: Check for updates on Debian-based systems
      shell: "apt list --upgradable"
      when: ansible_facts['os_family'] == 'Debian'
      register: apt_updates
      ignore_errors: true

    - name: Ensure dnf updates exist
      set_fact:
        dnf_updates_stdout: "{{ dnf_updates.stdout if dnf_updates.stdout is defined else '' }}"
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Ensure apt updates exist
      set_fact:
        apt_updates_stdout: "{{ apt_updates.stdout if apt_updates.stdout is defined else '' }}"
      when: ansible_facts['os_family'] == 'Debian'

    - name: Format output for each server with headers and footers
      set_fact:
        update_message: |
          -------------------------------
          {{ ansible_hostname }}:
          {% if dnf_updates_stdout %}
            DNF updates:
            {{ dnf_updates_stdout | indent(4) }}
          {% endif %}
          {% if apt_updates_stdout %}
            Apt updates:
            {{ apt_updates_stdout | indent(4) }}
          {% endif %}
          -------------------------------

    - name: Transfer output to the target server
      copy:
        content: "{{ update_message }}"
        dest: "/tmp/available_updates_{{ ansible_hostname }}.txt"
      when: inventory_hostname == "10.1.34.26"  # Target server for the output
      delegate_to: localhost
