- name: Check for available updates on Debian, RedHat, and Rocky Linux systems
  hosts: all
  become: yes
  tasks:
    - name: Gather facts about the system
      ansible.builtin.gather_facts:

    - name: Debug ansible_facts for Rocky Linux
      debug:
        var: ansible_facts
      when: ansible_facts['ansible_distribution'] == 'Rocky'

    - name: Get the hostname of the system
      shell: uname -n
      register: system_hostname

    - name: Check for available updates on Debian-based systems
      shell: apt list --upgradable
      when: ansible_facts['os_family'] == 'Debian'
      register: debian_updates
      ignore_errors: yes

    - name: Check for available updates on RedHat-based systems (using dnf)
      shell: dnf list updates
      when: ansible_facts['os_family'] == 'RedHat'
      register: redhat_updates
      ignore_errors: yes

    - name: Check for available updates on Rocky Linux systems (using dnf)
      shell: dnf list updates
      when: ansible_facts['ansible_distribution'] == 'Rocky'
      register: rocky_updates
      ignore_errors: yes

    - name: Ensure patchlist file exists and clear old contents on 10.1.34.26 (Debian)
      ansible.builtin.file:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        state: touch
      delegate_to: 10.1.34.26

    - name: Clear old contents of patchlist file on 10.1.34.26 (Debian)
      ansible.builtin.copy:
        dest: /home/svc_aux/backup/patchinformation/patchlist.txt
        content: ""
      when: ansible_facts['os_family'] == 'Debian'
      delegate_to: 10.1.34.26

    - name: Format and write updates to patchlist file on 10.1.34.26 (Debian)
      ansible.builtin.lineinfile:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        line: |
          -----------------------------------
          hostname: {{ system_hostname.stdout }}
          {{ debian_updates.stdout | replace('\n', '\n') }}
          -----------------------------
      when: ansible_facts['os_family'] == 'Debian'
      delegate_to: 10.1.34.26

    - name: Ensure patchlist file exists and clear old contents on 10.1.34.26 (RedHat)
      ansible.builtin.file:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        state: touch
      delegate_to: 10.1.34.26

    - name: Clear old contents of patchlist file on 10.1.34.26 (RedHat)
      ansible.builtin.copy:
        dest: /home/svc_aux/backup/patchinformation/patchlist.txt
        content: ""
      when: ansible_facts['os_family'] == 'RedHat'
      delegate_to: 10.1.34.26

    - name: Format and write updates to patchlist file on 10.1.34.26 (RedHat)
      ansible.builtin.lineinfile:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        line: |
          -----------------------------------
          hostname: {{ system_hostname.stdout }}
          {{ redhat_updates.stdout | replace('\n', '\n') }}
          -----------------------------
      when: ansible_facts['os_family'] == 'RedHat'
      delegate_to: 10.1.34.26

    - name: Ensure patchlist file exists and clear old contents on 10.1.34.26 (Rocky)
      ansible.builtin.file:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        state: touch
      delegate_to: 10.1.34.26

    - name: Clear old contents of patchlist file on 10.1.34.26 (Rocky)
      ansible.builtin.copy:
        dest: /home/svc_aux/backup/patchinformation/patchlist.txt
        content: ""
      when: ansible_facts['ansible_distribution'] == 'Rocky'
      delegate_to: 10.1.34.26

    - name: Format and write updates to patchlist file on 10.1.34.26 (Rocky)
      ansible.builtin.lineinfile:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        line: |
          -----------------------------------
          hostname: {{ system_hostname.stdout }}
          {{ rocky_updates.stdout | replace('\n', '\n') }}
          -----------------------------
      when: ansible_facts['ansible_distribution'] == 'Rocky'
      delegate_to: 10.1.34.26
