---
- name: Check for upgradable packages on servers
  hosts: all
  gather_facts: true
  tasks:
    - name: Check upgradable packages on Debian-based systems
      ansible.builtin.apt:
        update_cache: yes
      check_mode: yes
      register: apt_check
      when: ansible_os_family == "Debian"

    - name: Display upgradable packages on Debian-based systems
      ansible.builtin.debug:
        msg: "{{ apt_check.changes }}"
      when: ansible_os_family == "Debian"

    - name: Check upgradable packages on RedHat-based systems
      ansible.builtin.dnf:
        list: updates
      check_mode: yes
      register: dnf_check
      when: ansible_os_family == "RedHat"

    - name: Display upgradable packages on RedHat-based systems
      ansible.builtin.debug:
        msg: "{{ dnf_check.results }}"
      when: ansible_os_family == "RedHat"

    - name: Display message for unknown OS
      ansible.builtin.debug:
        msg: "Could not determine the OS for {{ inventory_hostname }}"
      when: ansible_os_family != "Debian" and ansible_os_family != "RedHat"
