---
- name: List available patches for Linux systems
  hosts: all
  become: yes
  vars:
    output_server: "10.1.34.26"
    output_file: "/home/svc_aux/backup/patchinformation/patchlist.txt"

  tasks:
    - name: Get hostname
      command: uname -n
      register: hostname
      changed_when: false

    - name: List available updates (Debian/Ubuntu)
      shell: apt list --upgradable 2>/dev/null | grep -v "Listing..." || echo "No updates available"
      register: debian_updates
      when: ansible_os_family == "Debian"

    - name: List available updates (RedHat/Rocky)
      shell: dnf check-update -q || echo "No updates available"
      register: redhat_updates
      when: ansible_os_family == "RedHat"

    - name: Generate patch list content
      set_fact:
        patch_content: >
          {% if ansible_os_family == "Debian" %}
          {% if debian_updates.stdout_lines | length > 0 and debian_updates.stdout != "No updates available" %}
          {{ debian_updates.stdout }}
          {% else %}
          No updates available
          {% endif %}
          {% elif ansible_os_family == "RedHat" %}
          {% if redhat_updates.stdout_lines | length > 0 and redhat_updates.stdout != "No updates available" %}
          {{ redhat_updates.stdout }}
          {% else %}
          No updates available
          {% endif %}
          {% endif %}

    - name: Write patch list to file on output server
      copy:
        content: "{{ hostname.stdout }}\n\n{{ patch_content }}\n"
        dest: "{{ output_file }}"
      delegate_to: "{{ output_server }}"
