---
- name: Check and list available updates for all servers
  hosts: all
  become: yes
  tasks:

    - name: Refresh the dnf cache before checking for updates (for Rocky Linux)
      command: dnf makecache
      when: ansible_facts['os_family'] == "RedHat"
      register: dnf_cache_refresh
      ignore_errors: yes

    - name: Check for available updates on Rocky Linux
      command: dnf list updates
      when: ansible_facts['os_family'] == "RedHat"
      register: redhat_updates
      ignore_errors: yes

    - name: Debug the output of dnf list updates (Rocky Linux)
      debug:
        msg: "{{ redhat_updates.stdout }}"
      when: ansible_facts['os_family'] == "RedHat"

    - name: Check for available updates on Debian-based systems
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == "Debian"
      register: debian_updates
      ignore_errors: yes

    - name: Debug the output of apt updates (Debian-based)
      debug:
        msg: "{{ debian_updates.stdout }}"
      when: ansible_facts['os_family'] == "Debian"

    - name: Display available updates for all systems
      debug:
        msg: |
          -----------------------------
          hostname : {{ ansible_facts['hostname'] }}
          {% if redhat_updates.stdout %}
            Available updates on Rocky Linux:
            {{ redhat_updates.stdout }}
          {% endif %}
          {% if debian_updates.stdout %}
            Available updates on Debian-based systems:
            {{ debian_updates.stdout }}
          {% endif %}
          -----------------------------
