---
- name: List available patches for Linux servers
  hosts: all
  become: yes
  vars:
    remote_server: "10.1.34.26"
    remote_path: "/home/svc_aux/backup/patchinformation/patchlist.csv"
    temp_file: "{{ lookup('ansible.builtin.tempfile') }}"
  tasks:
    - name: Identify the Linux distribution
      ansible.builtin.shell: |
        if [ -f /etc/os-release ]; then
          . /etc/os-release && echo $ID
        else
          echo "unknown"
        fi
      register: distro
      changed_when: false

    - name: Include tasks for Red Hat-based systems
      include_tasks: redhat_updates.yml
      when: distro.stdout in ["rhel", "centos", "rocky", "almalinux"]

    - name: Include tasks for Debian-based systems
      include_tasks: debian_updates.yml
      when: distro.stdout in ["debian", "ubuntu"]

    - name: Create local CSV file with headers
      ansible.builtin.copy:
        content: "Hostname,Package,Current Version,Available Version\n"
        dest: "{{ temp_file }}"
      delegate_to: localhost

    - name: Append patch information to local CSV file
      ansible.builtin.template:
        src: patch_info.j2
        dest: "{{ temp_file }}"
      delegate_to: localhost

    - name: Ensure remote directory exists
      ansible.builtin.file:
        path: "{{ remote_path | dirname }}"
        state: directory
      delegate_to: "{{ remote_server }}"

    - name: Copy CSV file to remote server
      ansible.builtin.copy:
        src: "{{ temp_file }}"
        dest: "{{ remote_path }}"
        mode: '0644'
      delegate_to: "{{ remote_server }}"

    - name: Remove temporary file
      ansible.builtin.file:
        path: "{{ temp_file }}"
        state: absent
      delegate_to: localhost
