---
- name: Check and list available updates for all servers
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Refresh the dnf cache before checking for updates (for Rocky Linux)
      when: ansible_facts['os_family'] in ["RedHat", "Rocky"]
      command: dnf makecache
      register: dnf_cache
      ignore_errors: yes

    - name: Check for available updates on Rocky Linux
      when: ansible_facts['os_family'] in ["RedHat", "Rocky"]
      command: dnf list updates
      register: dnf_updates
      ignore_errors: yes

    - name: Debug the output of dnf list updates (Rocky Linux)
      when: dnf_updates is defined
      debug:
        var: dnf_updates.stdout

    - name: Check for available updates on Debian-based systems
      when: ansible_facts['os_family'] == "Debian"
      command: apt list --upgradable
      register: apt_updates
      ignore_errors: yes

    - name: Debug the output of apt updates (Debian-based)
      when: apt_updates is defined
      debug:
        var: apt_updates.stdout

    - name: Display available updates for all systems
      debug:
        msg: |
          {{ inventory_hostname }}:
          {% if ansible_facts['os_family'] == 'Debian' %}
            Apt updates: 
            {{ apt_updates.stdout | default('No updates available or failed to fetch') }}
          {% elif ansible_facts['os_family'] in ['RedHat', 'Rocky'] %}
            DNF updates: 
            {{ dnf_updates.stdout | default('No updates available or failed to fetch') }}
          {% else %}
            Unknown OS family
          {% endif %}
