---
- name: Check for available updates on Debian and RedHat systems
  hosts: all
  become: true
  tasks:
    - name: Gather facts about the system
      ansible.builtin.setup:

    - name: Check for available updates on Debian-based systems
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_facts.os_family == "Debian"
      register: debian_updates

    - name: Debug message for Debian-based system
      ansible.builtin.debug:
        msg: "Running on Debian-based system. Updates: {{ debian_updates }}"

    - name: Show Debian system update list
      ansible.builtin.shell: |
        apt list --upgradable
      when: ansible_facts.os_family == "Debian"
      register: debian_update_list

    - name: Debug output for Debian system update list
      ansible.builtin.debug:
        msg: "Debian updates: {{ debian_update_list.stdout }}"
      when: ansible_facts.os_family == "Debian"

    - name: Check for available updates on RedHat-based systems
      ansible.builtin.yum:
        list: updates
      when: ansible_facts.os_family == "RedHat"
      register: redhat_updates

    - name: Debug message for RedHat-based system
      ansible.builtin.debug:
        msg: "Running on RedHat-based system. Updates: {{ redhat_updates }}"

    - name: Show RedHat system update list
      ansible.builtin.shell: |
        yum check-update
      when: ansible_facts.os_family == "RedHat"
      register: redhat_update_list

    - name: Debug output for RedHat system update list
      ansible.builtin.debug:
        msg: "RedHat updates: {{ redhat_update_list.stdout }}"
      when: ansible_facts.os_family == "RedHat"
