---
- name: Check for available updates
  hosts: all
  become: yes
  tasks:
    - name: Print OS family
      debug:
        msg: "OS Family: {{ ansible_os_family }}"

    - name: Check for updates on Debian-based systems
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: List available updates on Debian-based systems
      command: apt list --upgradable
      register: debian_updates
      when: ansible_os_family == "Debian"

    - name: Print available updates on Debian-based systems
      debug:
        msg: "{{ debian_updates.stdout_lines }}"
      when: ansible_os_family == "Debian"

    - name: Check for updates on Red Hat-based systems
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: List available updates on Red Hat-based systems
      command: yum check-update
      register: redhat_updates
      when: ansible_os_family == "RedHat"

    - name: Print available updates on Red Hat-based systems
      debug:
        msg: "{{ redhat_updates.stdout_lines }}"
      when: ansible_os_family == "RedHat"
