- name: Linux Patching Playbook
  hosts: all
  become: yes
  vars:
    output_server: "10.1.34.26"
    output_file: "/home/svc_aux/backup/patchinformation/patchlist.txt"

  tasks:
    - name: Get hostname
      command: uname -n
      register: hostname
      changed_when: false

    - name: List available updates (Debian)
      shell: apt list --upgradable
      register: debian_updates
      when: ansible_os_family == "Debian"

    - name: List available updates (RedHat)
      dnf:
        list: updates
      register: redhat_updates
      when: ansible_os_family == "RedHat"

    - name: Generate patch list content
      set_fact:
        patch_content: >
          {% if ansible_os_family == "Debian" %}
          {% if debian_updates.stdout_lines | length > 1 %}
          {{ debian_updates.stdout }}
          {% else %}
          No patches or updates available for this server
          {% endif %}
          {% elif ansible_os_family == "RedHat" %}
          {% if redhat_updates.results | length > 0 %}
          {% for package in redhat_updates.results %}
          {{ package.name }} - {{ package.version }}-{{ package.release }}
          {% endfor %}
          {% else %}
          No patches or updates available for this server
          {% endif %}
          {% endif %}

    - name: Write patch list to file on output server
      copy:
        content: "{{ hostname.stdout }}\n\n{{ patch_content }}\n"
        dest: "{{ output_file }}"
      delegate_to: "{{ output_server }}"
