---
- name: List available patches and save to file
  hosts: all
  become: yes
  tasks:
    - name: Get the hostname
      command: uname -n
      register: hostname

    - name: Check for available patches on RedHat-based systems
      shell: dnf list updates || true
      register: redhat_patches
      when: ansible_os_family == "RedHat"

    - name: Check for available patches on Debian-based systems
      shell: apt list --upgradable || true
      register: debian_patches
      when: ansible_os_family == "Debian"

    - name: Create or clear the patch list file
      file:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        state: touch
        mode: '0644'
      delegate_to: 10.1.34.26

    - name: Clear the contents of the patch list file
      copy:
        content: ''
        dest: /home/svc_aux/backup/patchinformation/patchlist.txt
      delegate_to: 10.1.34.26

    - name: Write hostname to file
      lineinfile:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        line: "Hostname: {{ hostname.stdout }}"
      delegate_to: 10.1.34.26

    - name: Write RedHat patches to file
      lineinfile:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        line: "{{ redhat_patches.stdout }}"
      when: redhat_patches.stdout is defined and redhat_patches.stdout != ""
      delegate_to: 10.1.34.26

    - name: Write Debian patches to file
      lineinfile:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        line: "{{ debian_patches.stdout }}"
      when: debian_patches.stdout is defined and debian_patches.stdout != ""
      delegate_to: 10.1.34.26

    - name: Write 'No patches available to upgrade' if no patches found
      lineinfile:
        path: /home/svc_aux/backup/patchinformation/patchlist.txt
        line: "No patches available to upgrade"
      when: (redhat_patches.stdout is not defined or redhat_patches.stdout == "") and (debian_patches.stdout is not defined or debian_patches.stdout == "")
      delegate_to: 10.1.34.26
