---
- name: Check for available updates on Debian and RedHat systems
  hosts: all
  become: true
  tasks:
    - name: Gather facts about the system
      ansible.builtin.setup:

    - name: Check for available updates on Debian-based systems
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_facts.os_family == "Debian"
      register: debian_updates

    - name: Display available updates on Debian-based systems
      ansible.builtin.debug:
        msg: "Debian updates: {{ debian_updates.upgrades | map(attribute='package') | join(', ') }}"
      when: ansible_facts.os_family == "Debian"
      when: debian_updates.upgrades is defined

    - name: Check for available updates on RedHat-based systems
      ansible.builtin.yum:
        list: updates
      when: ansible_facts.os_family == "RedHat"
      register: redhat_updates

    - name: Display available updates on RedHat-based systems
      ansible.builtin.debug:
        msg: "RedHat updates: {{ redhat_updates.updates | map(attribute='name') | join(', ') }}"
      when: ansible_facts.os_family == "RedHat"
      when: redhat_updates.updates is defined
