---
- name: Check File System Space
  hosts: all
  become: yes
  vars:
    min_space_mb: 500
    status_file: "/home/svc_aux/backup/patchstatus/filesystem_status.csv"

  tasks:
    - name: Initialize filesystem status
      set_fact:
        filesystem_status:
          hostname: "{{ inventory_hostname }}"
          status: "SUCCESS"

    - name: Check available space in filesystems
      ansible.builtin.shell: df -m {{ item }} | awk 'NR==2 {print $4}'
      register: available_space
      loop:
        - /
        - /boot
        - /var
      ignore_errors: yes

    - name: Verify sufficient space
      ansible.builtin.assert:
        that: "{{ item.stdout|int }} >= {{ min_space_mb }}"
        fail_msg: "Insufficient space in {{ item.item }}"
      loop: "{{ available_space.results }}"
      loop_control:
        label: "{{ item.item }}"
      register: space_check
      ignore_errors: yes

    - name: Set filesystem check status
      set_fact:
        filesystem_status: "{{ filesystem_status | combine({'status': 'FAILED'}) }}"
      when: space_check is failed

    - name: Ensure status file exists with header
      ansible.builtin.lineinfile:
        path: "{{ status_file }}"
        line: "hostname,status"
        create: yes
      delegate_to: 10.1.34.26
      run_once: true

    - name: Update filesystem status file
      ansible.builtin.lineinfile:
        path: "{{ status_file }}"
        line: "{{ filesystem_status.hostname }},{{ filesystem_status.status }}"
        insertafter: EOF
      delegate_to: 10.1.34.26

    - name: Display filesystem status
      ansible.builtin.debug:
        var: filesystem_status
