---
- name: Update Ubuntu servers
  hosts: all
  become: yes
  vars:
    min_space_mb: 500

  tasks:
    - name: Check available space in filesystems
      ansible.builtin.shell: df -m {{ item }} | awk 'NR==2 {print $4}'
      register: available_space
      loop:
        - /
        - /boot
        - /var
      
    - name: Verify sufficient space
      ansible.builtin.assert:
        that: "{{ item.stdout|int }} >= {{ min_space_mb }}"
        fail_msg: "Insufficient space in {{ item.item }}"
      loop: "{{ available_space.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Check if repos are up-to-date and valid
      ansible.builtin.command: apt-get update
      register: apt_update_result
      changed_when: false
      failed_when: apt_update_result.rc != 0

    - name: Perform system upgrade
      ansible.builtin.apt:
        upgrade: dist
      register: upgrade_result

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Display reboot status
      ansible.builtin.debug:
        msg: "Reboot is {{ 'required' if reboot_required.stat.exists else 'not required' }}"
