---
- name: Patch Ubuntu servers
  hosts: all
  become: yes
  vars:
    patch_status_file: "/home/svc_aux/backup/patchstatus/patchstatus.out"
    min_free_space_mb: 500  # Minimum free space required in MB
  tasks:
    - name: Check free space on /, /boot, and /var
      command: df -m --output=avail /
      register: root_fs
      changed_when: false

    - name: Check free space on /boot
      command: df -m --output=avail /boot
      register: boot_fs
      changed_when: false

    - name: Check free space on /var
      command: df -m --output=avail /var
      register: var_fs
      changed_when: false

    - name: Validate free space
      fail:
        msg: "Insufficient free space on {{ item.mount }}"
      when: item.avail < min_free_space_mb
      with_items:
        - { mount: '/', avail: "{{ root_fs.stdout_lines[1] | int }}" }
        - { mount: '/boot', avail: "{{ boot_fs.stdout_lines[1] | int }}" }
        - { mount: '/var', avail: "{{ var_fs.stdout_lines[1] | int }}" }

    - name: Check if all repositories are valid
      command: apt-get update
      register: apt_update
      changed_when: false
      failed_when: "'Err' in apt_update.stdout"

    - name: Patch the server
      apt:
        upgrade: dist
      register: apt_upgrade
      when: apt_update is succeeded

    - name: Check if reboot is required
      command: needs-restarting -r
      register: reboot_required
      changed_when: false
      when: apt_upgrade is succeeded

    - name: Gather patch status
      shell: uname -r
      register: kernel_version

    - name: Create patch status report
      lineinfile:
        path: "{{ patch_status_file }}"
        line: "Hostname: {{ inventory_hostname }}; Kernel: {{ kernel_version.stdout }}; File system status: Passed; Repo check: Passed; Patch status: Success; Updated patches: {{ apt_upgrade.stdout_lines }}; Reboot required: {{ 'Yes' if reboot_required.rc == 1 else 'No' }}"
        create: yes
      when: apt_upgrade is succeeded

    - name: Handle failure cases
      lineinfile:
        path: "{{ patch_status_file }}"
        line: "Hostname: {{ inventory_hostname }}; Kernel: {{ kernel_version.stdout }}; File system status: {{ 'Failed' if item.failed else 'Passed' }}; Repo check: {{ 'Failed' if apt_update.failed else 'Passed' }}; Patch status: Failed"
        create: yes
      when: item.failed or apt_update.failed
      with_items:
        - { failed: root_fs.failed or boot_fs.failed or var_fs.failed }
        - { failed: apt_update.failed }
      ignore_errors: yes
