---
- name: Check Repository Status
  hosts: ubuntu_servers
  become: yes
  vars:
    status_file: "/home/svc_aux/backup/patchstatus/repo_status.csv"

  tasks:
    - name: Remove existing status file
      ansible.builtin.file:
        path: "{{ status_file }}"
        state: absent
      delegate_to: 10.1.34.26
      run_once: true

    - name: Create new status file with header
      ansible.builtin.lineinfile:
        path: "{{ status_file }}"
        line: "hostname,status"
        create: yes
      delegate_to: 10.1.34.26
      run_once: true

    - name: Initialize repository status
      set_fact:
        repo_status:
          hostname: "{{ inventory_hostname }}"
          status: "SUCCESS"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      register: apt_update_result
      ignore_errors: yes

    - name: Check if repos are up-to-date and valid
      ansible.builtin.command: apt-get update
      args:
        warn: false
      register: apt_check_result
      changed_when: false
      failed_when: false

    - name: Set repository check status
      set_fact:
        repo_status: "{{ repo_status | combine({'status': 'FAILED'}) }}"
      when: apt_update_result is failed and apt_check_result.rc != 0

    - name: Update repository status file
      ansible.builtin.lineinfile:
        path: "{{ status_file }}"
        line: "{{ repo_status.hostname }},{{ repo_status.status }}"
        insertafter: EOF
      delegate_to: 10.1.34.26

    - name: Display repository status
      ansible.builtin.debug:
        var: repo_status
