---
- name: Check Filesystem, Repository Status, Patch Servers, and Check Reboot
  hosts: ubuntu_servers
  become: yes
  vars:
    min_space_mb: 500
    status_file: "/home/svc_aux/backup/patchstatus/system_status.csv"

  tasks:
    # [Previous tasks remain the same]

    # Patch servers only if both checks pass
    - name: Check for and apply updates
      block:
        - name: Check for available updates
          ansible.builtin.apt:
            update_cache: yes
          check_mode: yes
          register: update_check

        - name: Apply updates if available
          ansible.builtin.apt:
            upgrade: dist
            update_cache: yes
          when: update_check.changed
          register: patch_result

        - name: Get list of updated packages
          ansible.builtin.shell: grep -E "^Unpacking|^Setting up" /var/log/dpkg.log | tail -n 50 | awk '{print $4}' | sort | uniq
          register: updated_packages
          when: patch_result.changed

        - name: Check if reboot is required
          ansible.builtin.stat:
            path: /var/run/reboot-required
          register: reboot_required

        - name: Set patch status
          set_fact:
            system_status: "{{ system_status | combine({
              'patch_status': 'PATCHING SUCCESSFUL' if patch_result.changed else 'NO PATCHES AVAILABLE TO PATCH',
              'updated_packages': updated_packages.stdout_lines | default([]) | join(', '),
              'reboot_required': 'YES' if reboot_required.stat.exists else 'NO'
            }) }}"
      when:
        - system_status.filesystem_status == "SUCCESS"
        - system_status.repo_status == "SUCCESS"

    # Update Status File
    - name: Update status file
      ansible.builtin.lineinfile:
        path: "{{ status_file }}"
        line: "{{ system_status.hostname }},{{ system_status.filesystem_status }},{{ system_status.filesystem_details | replace(',', ';') }},{{ system_status.repo_status }},{{ system_status.repo_details | replace(',', ';') }},{{ system_status.patch_status }},{{ system_status.updated_packages | default('N/A') }},{{ system_status.reboot_required | default('N/A') }}"
        insertafter: EOF
      delegate_to: 10.1.34.26

    - name: Display system status
      ansible.builtin.debug:
        var: system_status
