---
- name: Patch Ubuntu servers
  hosts: all
  become: yes
  vars:
    patch_status_file: "/home/svc_aux/backup/patchstatus/patchstatus.out"
    min_free_space_mb: 1024  # Minimum free space required in MB
  tasks:
    - name: Check free space on /
      command: df -m --output=avail /
      register: root_fs
      changed_when: false

    - name: Check free space on /boot
      command: df -m --output=avail /boot
      register: boot_fs
      changed_when: false

    - name: Check free space on /var
      command: df -m --output=avail /var
      register: var_fs
      changed_when: false

    - name: Validate free space
      fail:
        msg: "Insufficient free space on {{ item.mount }}"
      when: item.avail | int < min_free_space_mb
      with_items:
        - { mount: '/', avail: "{{ root_fs.stdout_lines[1] }}" }
        - { mount: '/boot', avail: "{{ boot_fs.stdout_lines[1] }}" }
        - { mount: '/var', avail: "{{ var_fs.stdout_lines[1] }}" }
      ignore_errors: yes
      register: free_space_check

    - name: Check if all repositories are valid
      command: apt-get update
      register: apt_update
      changed_when: false
      failed_when: "'Err' in apt_update.stderr"
      ignore_errors: yes

    - name: Skip patching if checks failed
      meta: end_play
      when: free_space_check is failed or apt_update is failed

    - name: Patch the server
      apt:
        upgrade: dist
      register: apt_upgrade
      when: apt_update is succeeded
      ignore_errors: yes

    - name: Check if reboot is required
      command: needs-restarting -r
      register: reboot_required
      changed_when: false
      when: apt_upgrade is succeeded
      ignore_errors: yes

    - name: Gather patch status
      shell: uname -r
      register: kernel_version

    - name: Create patch status report
      lineinfile:
        path: "{{ patch_status_file }}"
        line: "Hostname: {{ inventory_hostname }}; File system check: {{ 'success' if free_space_check is succeeded else 'Failed' }}; Repo check: {{ 'success' if apt_update is succeeded else 'Failed' }}; Patch update: {{ 'success' if apt_upgrade is succeeded else 'Failed' }}; List of patches updated: {{ apt_upgrade.stdout_lines | join(' ') | default('No patches available to update') }}; Reboot required: {{ 'yes' if reboot_required.rc == 1 else 'No' }}"
        create: yes

    - name: Handle failure cases
      lineinfile:
        path: "{{ patch_status_file }}"
        line: "Hostname: {{ inventory_hostname }}; File system check: {{ 'Failed' if free_space_check is failed else 'success' }}; Repo check: {{ 'Failed' if apt_update is failed else 'success' }}; Patch update: Failed; List of patches updated: none; Reboot required: No"
        create: yes
      when: free_space_check is failed or apt_update is failed or apt_upgrade is failed
      ignore_errors: yes
