---
- name: Patch Ubuntu Servers with Filesystem Checks
  hosts: all
  gather_facts: no
  tasks:
    - name: Remove previous CSV content (if exists)
      file:
        path: /tmp/patch_status_report.csv
        state: absent

    - name: Create a new CSV file with headers
      copy:
        content: |
          Hostname, File system check, Repo check, Patch update, List of patches updated, Reboot required
        dest: /tmp/patch_status_report.csv
        mode: '0644'

    - name: Check disk space for root
      command: df -h /
      register: root_disk_space

    - name: Check disk space for /var
      command: df -h /var
      register: var_disk_space

    - name: Check disk space for /boot
      command: df -h /boot
      register: boot_disk_space

    - name: Check if repository is up to date
      command: apt-get update
      register: repo_status

    - name: Perform system update
      apt:
        upgrade: dist
      register: patch_result

    - name: Check if reboot is required
      command: needs-restarting
      register: reboot_required
      ignore_errors: yes

    - name: Append patch status to CSV file
      lineinfile:
        path: /tmp/patch_status_report.csv
        line: "{{ inventory_hostname }}, {{ root_disk_space.stdout }}, {{ var_disk_space.stdout }}, {{ boot_disk_space.stdout }}, {{ repo_status.stdout }}, {{ patch_result.stdout }}, {{ reboot_required.stdout }}"
        create: yes
