---
- name: Compare services after reboot
  hosts: all
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset: all

    - name: Create directory on remote server
      ansible.builtin.file:
        path: "/home/svc_aux/backup/files/{{ ansible_hostname }}"
        state: directory
      delegate_to: 10.1.34.26

    - name: Clear previous data after reboot
      ansible.builtin.file:
        path: "/home/svc_aux/backup/files/{{ ansible_hostname }}/running_services_after_reboot.txt"
        state: absent
      delegate_to: 10.1.34.26

    - name: Clear previous comparison result
      ansible.builtin.file:
        path: "/home/svc_aux/backup/files/{{ ansible_hostname }}/comparison_result.txt"
        state: absent
      delegate_to: 10.1.34.26

    - name: Collect running services after reboot
      ansible.builtin.shell: systemctl list-units --type=service --state=running | awk 'NR>1 {print $1}' | grep -v -e '^LOAD$' -e '^ACTIVE$' -e '^SUB$'
      register: running_services_after_reboot

    - name: Save running services after reboot to a file on remote server
      ansible.builtin.copy:
        content: "{{ running_services_after_reboot.stdout }}"
        dest: "/home/svc_aux/backup/files/{{ ansible_hostname }}/running_services_after_reboot.txt"
      delegate_to: 10.1.34.26

    - name: Check if before reboot file exists
      ansible.builtin.stat:
        path: "/home/svc_aux/backup/files/{{ ansible_hostname }}/running_services_before_reboot.txt"
      register: before_reboot_file
      delegate_to: 10.1.34.26

    - name: Check if after reboot file exists
      ansible.builtin.stat:
        path: "/home/svc_aux/backup/files/{{ ansible_hostname }}/running_services_after_reboot.txt"
      register: after_reboot_file
      delegate_to: 10.1.34.26

    - name: Compare services if both files exist
      ansible.builtin.shell: grep -Fxv -f /home/svc_aux/backup/files/{{ ansible_hostname }}/running_services_after_reboot.txt /home/svc_aux/backup/files/{{ ansible_hostname }}/running_services_before_reboot.txt
      register: diff_output
      when: before_reboot_file.stat.exists and after_reboot_file.stat.exists
      ignore_errors: yes

    - name: Save comparison result to a file on remote server
      ansible.builtin.copy:
        content: "{{ diff_output.stdout if diff_output is defined else 'No comparison data available' }}"
        dest: "/home/svc_aux/backup/files/{{ ansible_hostname }}/comparison_result.txt"
      delegate_to: 10.1.34.26
