---
- name: Compare services after reboot
  hosts: all
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset: all

    - name: Collect running services after reboot
      ansible.builtin.shell: systemctl list-units --type=service --state=running
      register: running_services_after_reboot

    - name: Save running services after reboot to a file on remote server
      ansible.builtin.copy:
        content: "{{ running_services_after_reboot.stdout }}"
        dest: "/home/svc_aux/backup/files/{{ ansible_hostname }}/running_services_after_reboot.txt"
      delegate_to: 10.1.34.26

    - name: Compare services
      ansible.builtin.shell: diff /home/svc_aux/backup/files/{{ ansible_hostname }}/running_services_before_reboot.txt /home/svc_aux/backup/files/{{ ansible_hostname }}/running_services_after_reboot.txt
      register: diff_output

    - name: Save comparison result to a file on remote server
      ansible.builtin.copy:
        content: "{{ diff_output.stdout }}"
        dest: "/home/svc_aux/backup/files/{{ ansible_hostname }}/comparison_result.txt"
      delegate_to: 10.1.34.26
