---
- name: Clean up old output on backup server
  hosts: 10.1.34.26
  remote_user: svc_aux
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
    - name: Find subdirectories under /home/svc_aux/backup/files
      ansible.builtin.find:
        paths: /home/svc_aux/backup/files
        file_type: directory
        depth: 1
      register: old_backup_dirs

    - name: Remove old output directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_backup_dirs.files }}"
      when: old_backup_dirs.matched > 0

- name: Save running services before reboot
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get the FQDN using hostname -f
      ansible.builtin.command: hostname -f
      register: fqdn_output
      when: inventory_hostname != '10.1.34.26'

    - name: Debug FQDN value (for troubleshooting)
      ansible.builtin.debug:
        var: fqdn_output.stdout
      when: inventory_hostname != '10.1.34.26'

    - name: Create directory using FQDN on backup server
      ansible.builtin.file:
        path: "/home/svc_aux/backup/files/{{ fqdn_output.stdout }}"
        state: directory
        mode: '0755'
      delegate_to: 10.1.34.26
      become: yes
      become_user: root
      when: inventory_hostname != '10.1.34.26'

    - name: Clear previous data before reboot
      ansible.builtin.file:
        path: "/home/svc_aux/backup/files/{{ fqdn_output.stdout }}/running_services_before_reboot.txt"
        state: absent
      delegate_to: 10.1.34.26
      become: yes
      become_user: root
      when: inventory_hostname != '10.1.34.26'

    - name: Collect running services before reboot
      ansible.builtin.shell: >
        systemctl list-units --type=service --state=running |
        awk 'NR>1 && $1 !~ /^(LOAD|ACTIVE|SUB)$/ {print $1}' |
        awk 'NF > 0'
      register: running_services_before_reboot
      when: inventory_hostname != '10.1.34.26'

    - name: Save running services before reboot to a file on backup server
      ansible.builtin.copy:
        content: "{{ running_services_before_reboot.stdout }}"
        dest: "/home/svc_aux/backup/files/{{ fqdn_output.stdout }}/running_services_before_reboot.txt"
        mode: '0644'
      delegate_to: 10.1.34.26
      become: yes
      become_user: root
      when: inventory_hostname != '10.1.34.26'

- name: Convert CSV to HTML on backup server
  hosts: 10.1.34.26
  remote_user: svc_aux
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: Convert CSV to HTML
      ansible.builtin.command: python3 /home/svc_aux/backup/files/new_convert.py
      args:
        chdir: /home/svc_aux/backup/files
