---
- name: Compare services after reboot
  hosts: all
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset: all

    - name: Get the hostname using uname -n
      ansible.builtin.command: uname -n
      register: uname_output

    - name: Create directory on remote server
      ansible.builtin.file:
        path: "/home/svc_aux/backup/files/{{ uname_output.stdout }}"
        state: directory
      delegate_to: 10.1.34.26

    - name: Clear previous data after reboot
      ansible.builtin.file:
        path: "/home/svc_aux/backup/files/{{ uname_output.stdout }}/running_services_after_reboot.txt"
        state: absent
      delegate_to: 10.1.34.26

    - name: Clear previous comparison result
      ansible.builtin.file:
        path: "/home/svc_aux/backup/files/{{ uname_output.stdout }}/comparison_result.txt"
        state: absent
      delegate_to: 10.1.34.26

    - name: Collect running services after reboot
      ansible.builtin.shell: systemctl list-units --type=service --state=running | awk 'NR>1 && $1 !~ /^(LOAD|ACTIVE|SUB)$/ {print $1}' | awk 'NF > 0'
      register: running_services_after_reboot

    - name: Save running services after reboot to a file on remote server
      ansible.builtin.copy:
        content: "{{ running_services_after_reboot.stdout }}"
        dest: "/home/svc_aux/backup/files/{{ uname_output.stdout }}/running_services_after_reboot.txt"
      delegate_to: 10.1.34.26

    - name: Check if before reboot file exists
      ansible.builtin.stat:
        path: "/home/svc_aux/backup/files/{{ uname_output.stdout }}/running_services_before_reboot.txt"
      register: before_reboot_file
      delegate_to: 10.1.34.26

    - name: Check if after reboot file exists
      ansible.builtin.stat:
        path: "/home/svc_aux/backup/files/{{ uname_output.stdout }}/running_services_after_reboot.txt"
      register: after_reboot_file
      delegate_to: 10.1.34.26

    - name: Compare services if both files exist
      ansible.builtin.shell: |
        if [ -f /home/svc_aux/backup/files/{{ uname_output.stdout }}/running_services_before_reboot.txt ] && [ -f /home/svc_aux/backup/files/{{ uname_output.stdout }}/running_services_after_reboot.txt ]; then
          diff_output=$(grep -Fxv -f /home/svc_aux/backup/files/{{ uname_output.stdout }}/running_services_after_reboot.txt /home/svc_aux/backup/files/{{ uname_output.stdout }}/running_services_before_reboot.txt)
          if [ -z "$diff_output" ]; then
            echo "All services that were running before the reboot are still running after the reboot."
          else
            echo "$diff_output"
          fi
        else
          echo "One or both of the files do not exist."
        fi
      register: diff_output
      ignore_errors: yes

    - name: Save comparison result to a file on remote server
      ansible.builtin.copy:
        content: "{{ diff_output.stdout }}"
        dest: "/home/svc_aux/backup/files/{{ uname_output.stdout }}/comparison_result.txt"
      delegate_to: 10.1.34.26
