---
- name: Collect system information and send to remote server
  hosts: all
  gather_facts: true
  become: true

  vars:
    remote_server: "10.1.128.84"
    backup_user: "svc_aux"
    remote_password: "just44now"
    remote_path: "/home/svc_aux/backup"
    output_file: "/tmp/system_info_{{ inventory_hostname }}_{{ ansible_date_time.iso8601_basic }}.log"

  tasks:
    - name: Generate system information output file on the remote server
      shell: |
        echo "==== Process Information ====" > {{ output_file }}
        ps aux | grep -E 'httpd|nginx|apache2' || echo "Command not available: ps aux for web servers" >> {{ output_file }}
        ps aux | grep -E 'mysql|mariadb' || echo "Command not available: ps aux for mysql/mariadb" >> {{ output_file }}
        ps aux | grep postgres || echo "Command not available: ps aux for postgres" >> {{ output_file }}
        ps aux | grep pmon || echo "Command not available: ps aux for pmon" >> {{ output_file }}
        ps aux | grep mongo || echo "Command not available: ps aux for mongo" >> {{ output_file }}
        ps aux | grep -E 'mysql|mariadb|postgres|oracle|mongo|mssql' || echo "Command not available: ps aux for database services" >> {{ output_file }}
        ps aux || echo "Command not available: ps aux" >> {{ output_file }}
        ps -ef || echo "Command not available: ps -ef" >> {{ output_file }}
        echo "==== Web Server Configurations ====" >> {{ output_file }}
        nginx -T 2>/dev/null || echo "Command not available: nginx -T" >> {{ output_file }}
        apache2 -S 2>/dev/null || echo "Command not available: apache2 -S" >> {{ output_file }}
        apache2ctl -S 2>/dev/null || echo "Command not available: apache2ctl -S" >> {{ output_file }}
        httpd -S 2>/dev/null || echo "Command not available: httpd -S" >> {{ output_file }}

        echo "==== Open Ports and Connections ====" >> {{ output_file }}
        netstat -plant || echo "Command not available: netstat -plant" >> {{ output_file }}
        netstat -tulpn || echo "Command not available: netstat -tulpn" >> {{ output_file }}
        netstat -tulnp | grep -E '80|443' || echo "Command not available: netstat for ports 80/443" >> {{ output_file }}
        ss || echo "Command not available: ss" >> {{ output_file }}
        netstat -plant | grep -i listen || echo "Command not available: netstat for listen" >> {{ output_file }}

        echo "==== System Services Status ====" >> {{ output_file }}
        systemctl status mysql || echo "Service not available: mysql" >> {{ output_file }}
        systemctl status mariadb || echo "Service not available: mariadb" >> {{ output_file }}
        systemctl status postgresql || echo "Service not available: postgresql" >> {{ output_file }}
        lsnrctl status || echo "Service not available: lsnrctl" >> {{ output_file }}
        systemctl status mongod || echo "Service not available: mongod" >> {{ output_file }}
        systemctl status mssql-server || echo "Service not available: mssql-server" >> {{ output_file }}
        systemctl status apache2.service || echo "Service not available: apache2" >> {{ output_file }}
        systemctl status php-fpm || echo "Service not available: php-fpm" >> {{ output_file }}
        systemctl list-units --state=running || echo "Command not available: systemctl list-units" >> {{ output_file }}
        systemctl list-unit-files || echo "Command not available: systemctl list-unit-files" >> {{ output_file }}

        echo "==== Web Server Configurations ====" >> {{ output_file }}
        grep -R "ServerName" /etc/httpd/ || echo "Command not available: grep ServerName in /etc/httpd/" >> {{ output_file }}
        grep -R "ServerName" /etc/apache2/ || echo "Command not available: grep ServerName in /etc/apache2/" >> {{ output_file }}
        grep -R "server_name" /etc/nginx/ || echo "Command not available: grep server_name in /etc/nginx/" >> {{ output_file }}
        grep DocumentRoot /etc/httpd/conf/httpd.conf || echo "Command not available: grep DocumentRoot in /etc/httpd/" >> {{ output_file }}
        grep DocumentRoot /etc/apache2/sites-available/*.conf || echo "Command not available: grep DocumentRoot in /etc/apache2/sites-available/" >> {{ output_file }}
        grep root /etc/nginx/sites-available/*.conf || echo "Command not available: grep root in /etc/nginx/sites-available/" >> {{ output_file }}
        grep -Ri "DocumentRoot" /etc/apache2/ || echo "Command not available: grep DocumentRoot recursively in /etc/apache2/" >> {{ output_file }}
        grep -Ri "server_name" /etc/nginx/ || echo "Command not available: grep server_name recursively in /etc/nginx/" >> {{ output_file }}
        grep -Ri "fastcgi_pass" /etc/nginx/ || echo "Command not available: grep fastcgi_pass recursively in /etc/nginx/" >> {{ output_file }}

        echo "==== PHP Information ====" >> {{ output_file }}
        php -v || echo "Command not available: php -v" >> {{ output_file }}
        php -m || echo "Command not available: php -m" >> {{ output_file }}
        apachectl -M | grep php || echo "Command not available: apachectl for php" >> {{ output_file }}

        echo "==== Docker Information ====" >> {{ output_file }}
        docker ps || echo "Command not available: docker ps" >> {{ output_file }}
        docker ps -a || echo "Command not available: docker ps -a" >> {{ output_file }}
        docker images -a || echo "Command not available: docker images -a" >> {{ output_file }}
        docker images || echo "Command not available: docker images" >> {{ output_file }}

        echo "==== System Information ====" >> {{ output_file }}
        uname -a || echo "Command not available: uname -a" >> {{ output_file }}
        ifconfig -a || echo "Command not available: ifconfig -a" >> {{ output_file }}
        ip a || echo "Command not available: ip a" >> {{ output_file }}
        ip route show || echo "Command not available: ip route show" >> {{ output_file }}
        netstat -nr || echo "Command not available: netstat -nr" >> {{ output_file }}
        fdisk -l || echo "Command not available: fdisk -l" >> {{ output_file }}
        rpm -qa --last || echo "Command not available: rpm -qa" >> {{ output_file }}
        vgdisplay || echo "Command not available: vgdisplay" >> {{ output_file }}
        lvdisplay || echo "Command not available: lvdisplay" >> {{ output_file }}
        pvs || echo "Command not available: pvs" >> {{ output_file }}
        vgs || echo "Command not available: vgs" >> {{ output_file }}
        lsblk -d || echo "Command not available: lsblk -d" >> {{ output_file }}
        lsblk || echo "Command not available: lsblk" >> {{ output_file }}
        blkid || echo "Command not available: blkid" >> {{ output_file }}
        lsscsi || echo "Command not available: lsscsi" >> {{ output_file }}
        cat /etc/fstab || echo "Command not available: cat /etc/fstab" >> {{ output_file }}
        cat /etc/resolv.conf || echo "Command not available: cat /etc/resolv.conf" >> {{ output_file }}
        mount || echo "Command not available: mount" >> {{ output_file }}
        cat /etc/*release || echo "Command not available: cat /etc/*release" >> {{ output_file }}
        cat /etc/hosts || echo "Command not available: cat /etc/hosts" >> {{ output_file }}
        ls -l /dev/mapper || echo "Command not available: ls -l /dev/mapper" >> {{ output_file }}
        cat /boot/grub/menu.lst || echo "Command not available: cat /boot/grub/menu.lst" >> {{ output_file }}
        cat /boot/grub2/grub.cfg | grep -v ^# || echo "Command not available: cat /boot/grub2/grub.cfg" >> {{ output_file }}
        cat /boot/grub2/grub.cfg || echo "Command not available: cat /boot/grub2/grub.cfg" >> {{ output_file }}
        lvs || echo "Command not available: lvs" >> {{ output_file }}
        lvs -a -o+devices || echo "Command not available: lvs -a -o+devices" >> {{ output_file }}
      args:
        warn: false

    - name: Fetch the system information file to Ansible Controller
      fetch:
        src: "{{ output_file }}"
        dest: "./logs/{{ inventory_hostname }}/"
        flat: yes

    - name: Copy logs from Ansible Controller to remote backup server
      delegate_to: localhost
      copy:
        src: "./logs/{{ inventory_hostname }}/system_info_{{ inventory_hostname }}_{{ ansible_date_time.iso8601_basic }}.log"
        dest: "{{ remote_path }}/system_info_{{ inventory_hostname }}_{{ ansible_date_time.iso8601_basic }}.log"
