---
- name: Execute commands and store output
  hosts: all
  tasks:
    - name: Create output file
      shell: touch /tmp/{{ inventory_hostname }}_{{ ansible_date_time.date }}.out

    - name: Execute commands and append output to file
      shell: |
        {
          echo "==== Process Information ====";
          ps aux | grep -E 'httpd|nginx|apache2' || echo "command not available";
          ps aux | grep -E 'mysql|mariadb' || echo "command not available";
          ps aux | grep postgres || echo "command not available";
          ps aux | grep pmon || echo "command not available";
          ps aux | grep mongo || echo "command not available";
          ps aux | grep -E 'mysql|mariadb|postgres|oracle|mongo|mssql' || echo "command not available";
          ps aux || echo "command not available";
          ps -ef || echo "command not available";

          echo "==== Web Server Configurations ====";
          nginx -T 2>/dev/null || echo "command not available";
          apache2 -S 2>/dev/null || echo "command not available";
          apache2ctl -S 2>/dev/null || echo "command not available";
          httpd -S 2>/dev/null || echo "command not available";

          echo "==== Open Ports and Connections ====";
          netstat -plant || echo "command not available";
          netstat -tulpn || echo "command not available";
          netstat -tulnp | grep -E '80|443' || echo "command not available";
          ss || echo "command not available";
          netstat -plant | grep -i listen || echo "command not available";

          echo "==== System Services Status ====";
          systemctl status mysql || echo "command not available";
          systemctl status mariadb || echo "command not available";
          systemctl status postgresql || echo "command not available";
          lsnrctl status || echo "command not available";
          systemctl status mongod || echo "command not available";
          systemctl status mssql-server || echo "command not available";
          systemctl status apache2.service || echo "command not available";
          systemctl status php-fpm || echo "command not available";
          systemctl list-units --state=running || echo "command not available";
          systemctl list-unit-files || echo "command not available";

          echo "==== Web Server Configurations ====";
          grep -R "ServerName" /etc/httpd/ || echo "command not available";
          grep -R "ServerName" /etc/apache2/ || echo "command not available";
          grep -R "server_name" /etc/nginx/ || echo "command not available";
          grep DocumentRoot /etc/httpd/conf/httpd.conf || echo "command not available";
          grep DocumentRoot /etc/apache2/sites-available/*.conf || echo "command not available";
          grep root /etc/nginx/sites-available/*.conf || echo "command not available";
          grep -Ri "DocumentRoot" /etc/apache2/ || echo "command not available";
          grep -Ri "server_name" /etc/nginx/ || echo "command not available";
          grep -Ri "fastcgi_pass" /etc/nginx/ || echo "command not available";

          echo "==== PHP Information ====";
          php -v || echo "command not available";
          php -m || echo "command not available";
          apachectl -M | grep php || echo "command not available";

          echo "==== Docker Information ====";
          docker ps || echo "command not available";
          docker ps -a || echo "command not available";
          docker images -a || echo "command not available";
          docker images || echo "command not available";

          echo "==== System Information ====";
          uname -a || echo "command not available";
          ifconfig -a || echo "command not available";
          ip a || echo "command not available";
          ip route show || echo "command not available";
          netstat -nr || echo "command not available";
          fdisk -l || echo "command not available";
          rpm -qa --last || echo "command not available";
          vgdisplay || echo "command not available";
          lvdisplay || echo "command not available";
          pvs || echo "command not available";
          vgs || echo "command not available";
          lsblk -d || echo "command not available";
          lsblk || echo "command not available";
          blkid || echo "command not available";
          lsscsi || echo "command not available";
          cat /etc/fstab || echo "command not available";
          cat /etc/resolv.conf || echo "command not available";
          mount || echo "command not available";
          cat /etc/*release || echo "command not available";
          cat /etc/hosts || echo "command not available";
          ls -l /dev/mapper || echo "command not available";
          cat /boot/grub/menu.lst || echo "command not available";
          cat /boot/grub2/grub.cfg | grep -v ^# || echo "command not available";
          cat /boot/grub2/grub.cfg || echo "command not available";
          lvs -a -o +devices -P || echo "command not available";
          lvs --segments || echo "command not available";
          lvs -o+lv_layout,stripes || echo "command not available";
          lvs -a -o+lv_layout,lv_role,stripes,devices || echo "command not available";
          free -g || echo "command not available";
          lscpu || echo "command not available";
          df -h || echo "command not available";
          cat /etc/passwd || echo "command not available";
          cat /etc/shadow || echo "command not available";
          cat /etc/group || echo "command not available";
          ls -l /boot/ || echo "command not available";
        } >> /tmp/{{ inventory_hostname }}_{{ ansible_date_time.date }}.out 2>&1
      ignore_errors: yes

    - name: Ensure destination directory exists on remote server
      ansible.builtin.shell: mkdir -p /home/svc_aux/backup
      delegate_to: 10.1.128.84

    - name: Fetch output file to controller
      ansible.builtin.fetch:
        src: /tmp/{{ inventory_hostname }}_{{ ansible_date_time.date }}.out
        dest: /tmp/
        flat: yes

    - name: Copy output file to remote server
      ansible.builtin.shell: |
        scp /tmp/{{ inventory_hostname }}_{{ ansible_date_time.date }}.out svc_aux@10.1.128.84:/home/svc_aux/backup/
      delegate_to: localhost
      vars:
        ansible_ssh_pass: just44now
