---
- name: Compare services after reboot
  hosts: all
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset: all

    - name: Get the hostname with domain using hostname -f
      ansible.builtin.command: hostname -f
      register: fqdn_output

    - name: Create directory using FQDN
      ansible.builtin.file:
        path: "/home/svc_aux/backup/files/{{ fqdn_output.stdout }}"
        state: directory
      delegate_to: 10.1.34.26

    - name: Clear previous data after reboot
      ansible.builtin.file:
        path: "/home/svc_aux/backup/files/{{ fqdn_output.stdout }}/running_services_after_reboot.txt"
        state: absent
      delegate_to: 10.1.34.26

    - name: Clear previous comparison result
      ansible.builtin.file:
        path: "/home/svc_aux/backup/files/{{ fqdn_output.stdout }}/comparison_result.txt"
        state: absent
      delegate_to: 10.1.34.26

- name: Compare services and generate reports
  hosts: 10.1.34.26
  remote_user: svc_aux
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  tasks:
    - name: Collect running services after reboot
      ansible.builtin.shell: >
        systemctl list-units --type=service --state=running |
        awk 'NR>1 && $1 !~ /^(LOAD|ACTIVE|SUB)$/ {print $1}' |
        awk 'NF > 0'
      register: running_services_after_reboot

    - name: Save running services after reboot to a file on remote server
      ansible.builtin.copy:
        content: "{{ running_services_after_reboot.stdout }}"
        dest: "/home/svc_aux/backup/files/{{ fqdn_output.stdout }}/running_services_after_reboot.txt"
      delegate_to: 10.1.34.26

    - name: Compare services and save the result using bash
      ansible.builtin.shell: |
        bash -c '
        diff_output=$(comm -23 <(sort /home/svc_aux/backup/files/{{ fqdn_output.stdout }}/running_services_before_reboot.txt) <(sort /home/svc_aux/backup/files/{{ fqdn_output.stdout }}/running_services_after_reboot.txt))
        if [ -z "$diff_output" ]; then
          echo "All services that were running before the reboot are still running after the reboot." > /home/svc_aux/backup/files/{{ fqdn_output.stdout }}/comparison_result.txt
        else
          echo "Services not running after reboot:" > /home/svc_aux/backup/files/{{ fqdn_output.stdout }}/comparison_result.txt
          echo "$diff_output" >> /home/svc_aux/backup/files/{{ fqdn_output.stdout }}/comparison_result.txt
        fi
        '
      delegate_to: 10.1.34.26
