---
- name: Upgrade Ubuntu to the next available version
  hosts: all
  become: yes
  tasks:
    - name: Update APT repository
      apt:
        update_cache: yes

    - name: Upgrade to the latest packages
      apt:
        upgrade: dist

    - name: Install update-manager-core if not already installed
      apt:
        name: update-manager-core
        state: present

    - name: Upgrade Ubuntu version
      command: |
        do-release-upgrade -f DistUpgradeViewNonInteractive
      register: upgrade_result
      ignore_errors: yes

    - name: Check if the system needs a reboot
      reboot:
      when: upgrade_result.changed

    - name: Notify about the upgrade status
      debug:
        msg: "Upgrade process finished. Check the system for the new version."
