---
- hosts: all
  become: yes
  vars:
    # Ensure that the default answer is chosen automatically during the package installation
    apt_options: '-y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"'

  tasks:
    - name: Remove unused packages and dependencies
      ansible.builtin.apt:
        autoremove: yes
        dpkg_options: "{{ apt_options }}"
      tags: autoremove

    - name: Clean the local repository of retrieved package files
      ansible.builtin.apt:
        autoclean: yes
        dpkg_options: "{{ apt_options }}"
      tags: autoclean

    - name: Update the apt package index
      ansible.builtin.apt:
        update_cache: yes
      tags: update

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
        dpkg_options: "{{ apt_options }}"
      tags: upgrade

    - name: Reboot the server if the kernel was updated
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for kernel updates."
        reboot_timeout: 600
      when: "'linux-image' in ansible_facts.packages"
      tags: reboot
