---
- name: Gather system configuration and backup files
  hosts: all
  become: true
  tasks:
    - name: Create base output directory
      file:
        path: /backup/config
        state: directory
        mode: '0775'

    - name: Create backup directories
      file:
        path: "/backup/config/{{ item }}"
        state: directory
        mode: '0775'
      loop:
        - postgres-config-backup
        - apache2-config-backup
        - nginx-config-backup
        - mysql-config-backup
        - passwd-backup
        - group-backup
        - shadow-backup
        - fstab-backup

    - name: Execute commands and save output to a file
      shell: |
        {
          echo "### uname -a ###"
          uname -a
          echo "### ps aux ###"
          ps aux
          echo "### ps -ef ###"
          ps -ef
          echo "### ifconfig -a ###"
          ifconfig -a
          echo "### ip a ###"
          ip a
          echo "### ip route show ###"
          ip route show
          echo "### netstat -nr ###"
          netstat -nr
          echo "### fdisk -l ###"
          fdisk -l
          echo "### dpkg-query -l ###"
          dpkg-query -l
          echo "### dpkg-query -s ###"
          dpkg-query -s
          echo "### apt list --installed ###"
          apt list --installed
          echo "### vgdisplay ###"
          vgdisplay
          echo "### lvdisplay ###"
          lvdisplay
          echo "### pvs ###"
          pvs
          echo "### vgs ###"
          vgs
          echo "### lsblk -d ###"
          lsblk -d
          echo "### lsblk ###"
          lsblk
          echo "### blkid ###"
          blkid
          echo "### lsscsi ###"
          lsscsi
          echo "### cat /etc/fstab ###"
          cat /etc/fstab
          echo "### cat /etc/resolv.conf ###"
          cat /etc/resolv.conf
          echo "### mount ###"
          mount
          echo "### cat /etc/*release ###"
          cat /etc/*release
          echo "### cat /etc/hosts ###"
          cat /etc/hosts
          echo "### ls -l /dev/mapper ###"
          ls -l /dev/mapper
          echo "### cat /boot/grub/menu.lst ###"
          cat /boot/grub/menu.lst
          echo "### ss ###"
          ss
          echo "### lsof -i ###"
          lsof -i
          echo "### systemctl list-units --state=running ###"
          systemctl list-units --state=running
          echo "### systemctl list-unit-files ###"
          systemctl list-unit-files
          echo "### cat /etc/passwd ###"
          cat /etc/passwd
          echo "### cat /etc/shadow ###"
          cat /etc/shadow
          echo "### cat /etc/group ###"
          cat /etc/group
          echo "### cat /boot/grub/grub.cfg | grep -v ^# ###"
          cat /boot/grub/grub.cfg | grep -v ^#
          echo "### cat /boot/grub/grub.cfg ###"
          cat /boot/grub/grub.cfg
          echo "### ls -l /boot/ ###"
          ls -l /boot/
          echo "### lvs -a -o +devices -P ###"
          lvs -a -o +devices -P
          echo "### lvs --segments ###"
          lvs --segments
          echo "### lvs -o+lv_layout,stripes ###"
          lvs -o+lv_layout,stripes
          echo "### lvs -a -o+lv_layout,lv_role,stripes,devices ###"
          lvs -a -o+lv_layout,lv_role,stripes,devices
          echo "### free -g ###"
          free -g
          echo "### lscpu ###"
          lscpu
          echo "### df -hT ###"
          df -hT
          echo "### df -h -x devtmpfs -x tmpfs | grep -v \"snapshot\" ###"
          df -h -x devtmpfs -x tmpfs | grep -v "snapshot"
          echo "### ip a|grep -i \"inet\" |grep -i ens* ###"
          ip a|grep -i "inet" |grep -i ens*
          echo "### cat /var/log/dpkg.log* ###"
          cat /var/log/dpkg.log*
          echo "### dpkg -l ###"
          dpkg -l
          echo "### dpkg -s ###"
          dpkg -s
        }
      args:
        creates: "/backup/config/system_configuration_output_{{ ansible_date_time.date }}.txt"
        executable: /bin/bash
        chdir: /

    - name: Backup system configuration files
      copy:
        src: "{{ item.src }}"
        dest: "/backup/config/{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      loop:
        - { src: '/etc/ssh/', dest: 'ssh-config-backup/' }
        - { src: '/etc/passwd', dest: 'passwd-backup/passwd.old' }
        - { src: '/etc/group', dest: 'group-backup/group.old' }
        - { src: '/etc/shadow', dest: 'shadow-backup/shadow.old' }
        - { src: '/etc/fstab', dest: 'fstab-backup/fstab.old' }
        - { src: '/etc/apache2/', dest: 'apache2-config-backup/' }
        - { src: '/etc/nginx/', dest: 'nginx-config-backup/' }
        - { src: '/etc/mysql/my.cnf', dest: 'mysql-config-backup/' }
        - { src: '/etc/postgresql/13/main/postgresql.conf', dest: 'postgres-config-backup/postgresql.conf' }
        - { src: '/etc/postgresql/13/main/pg_hba.conf', dest: 'postgres-config-backup/pg_hba.conf' }
      register: copy_results
      failed_when: item.rc != 0 and item.results is defined

