---
- name: Upgrade Ubuntu to the next available version
  hosts: all
  become: yes
  tasks:
    - name: Fix broken dependencies
      apt:
        name: ''
        state: latest
        update_cache: yes
        force: yes
      register: fix_broken_result
      ignore_errors: yes

    - name: Check if there were broken dependencies
      fail:
        msg: "Fixing broken dependencies failed. Manual intervention is required."
      when: fix_broken_result is failed

    - name: Update APT repository
      apt:
        update_cache: yes
      register: update_cache_result
      retries: 5
      delay: 10
      until: update_cache_result is succeeded

    - name: Upgrade to the latest packages
      apt:
        upgrade: dist
      register: upgrade_result
      retries: 5
      delay: 10
      until: upgrade_result is succeeded

    - name: Install update-manager-core if not already installed
      apt:
        name: update-manager-core
        state: present

    - name: Upgrade Ubuntu version
      command: |
        do-release-upgrade -f DistUpgradeViewNonInteractive
      register: upgrade_result
      ignore_errors: yes

    - name: Check if the system needs a reboot
      reboot:
      when: upgrade_result.changed

    - name: Notify about the upgrade status
      debug:
        msg: "Upgrade process finished. Check the system for the new version."
