---
- name: Patch Windows Servers
  hosts: all
  gather_facts: yes
  tasks:
    - name: Install Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
      register: update_result

    - name: Reboot system if required
      win_reboot:
        reboot_timeout: 600
        test_command: whoami
      when: update_result.reboot_required

    - name: Display update status
      debug:
        msg: "Updates completed successfully."
      when: update_result.updates_installed | length > 0

    - name: No updates needed
      debug:
        msg: "No updates were installed."
      when: update_result.updates_installed | length == 0
