- name: Restart Windows Explorer
  hosts: all
  gather_facts: no
  tasks:
    - name: Stop explorer.exe
      ansible.windows.win_shell: |
        Stop-Process -Name explorer -Force
      ignore_errors: yes  # Explorer is not always running

    - name: Start explorer.exe
      ansible.windows.win_shell: |
        Start-Process explorer.exe
