- name: Restart Windows Explorer
  hosts: all
  gather_facts: no
  tasks:
    - name: Stop explorer.exe
      win_shell: |
        Stop-Process -Name explorer -Force
      ignore_errors: yes

    - name: Start explorer.exe
      win_shell: |
        Start-Process explorer.exe
